### ISSUE TITLE
Upgrade to Cabal 3.10.1.0

### ISSUE THREAD

**Issue by tfausak** [acilearning/docker-haskell#34]
https://discourse.haskell.org/t/just-released-cabal-3-10-1-0/5978

This release changes some of the folders used by Cabal. It used to be that everything was under `~/.cabal`, but now it will follow to XDG spec. This change doesn't affect the image per se, but users of this image may need to change some stuff.

**Comment by codygman** [comment]
I'm happy it'll change to XDG, but from experience I know this can break some things, especially if backwards compatibility is preserved for `~/.cabal`.

**Comment by tfausak** [comment]
I looked into this a little bit. I think we could simply upgrade to Cabal 3.10.1.0 and everything would continue working as configured. That's because Cabal takes the presence of `~/.cabal` to mean "don't use XDG dirs". We create `~/.cabal` in the `Dockerfile`, so Cabal will continue to use that. 

However, we may want to switch over to using the XDG dirs. It would arguably make caching simpler, since you could cache `~/.local/state` (the Cabal store is in here) and `~/.cache` (the Hackage index is in here). 

Also GHCup can be configured to use XDG dirs using [`GHCUP_USE_XDG_DIRS=1`](https://www.haskell.org/ghcup/guide/#xdg-support). The main consequence of that for us would be GHCup using `~/.local/bin` instead of `~/.ghcup/bin`, which would simplify `PATH` stuff a little bit. 

It's not really related to all this, but I wonder if changing the Cabal store from `~/.cabal/store` (or `~/.local/state/cabal/store` with XDG) to `/cabal-store` is even worth it. It adds some extra configuration and would only matter if you used a different user inside the container. But if you use a different user, you'd have to re-set the configuration anyway, at which point you could just set it to `/home/haskell/...`.
